services:
  - type: web
    name: swing-scanner-dashboard
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "streamlit run swing_dashboard.py"
    envVars:
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ALERT_EMAIL
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
